POST https://node-api-simple-deploy.onrender.com/videos
Content-Type: application/json

{
    "title": "Título especial ATT",
    "description": "Descrição",
    "duration": 100
}

###

GET https://node-api-simple-deploy.onrender.com/videos?search=ATT

###

PUT https://node-api-simple-deploy.onrender.com/videos/9735f5ff-b681-42f0-8196-c388b2ea685d
Content-Type: application/json

{
    "title": "Título ATT 2",
    "description": "Descrição ATT",
    "duration": 200
}

###

DELETE https://node-api-simple-deploy.onrender.com/videos/9735f5ff-b681-42f0-8196-c388b2ea685d